# Generated by Django 4.2.16 on 2026-05-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to MLM Network', max_length=200)),
                ('hero_subtitle', models.TextField(default='Build Your Financial Freedom with Our Proven MLM System')),
                ('hero_button_text', models.CharField(default='Get Started', max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('about_title', models.CharField(default='About Us', max_length=200)),
                ('about_description', models.TextField(default='We are a leading MLM platform...')),
                ('features_title', models.CharField(default='Why Choose Us', max_length=200)),
                ('total_members', models.IntegerField(default=10000)),
                ('total_earnings', models.CharField(default='₹1 Crore+', max_length=50)),
                ('success_rate', models.CharField(default='95%', max_length=50)),
                ('countries', models.IntegerField(default=5)),
                ('contact_email', models.EmailField(default='support@mlmnetwork.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91-XXXXXXXXXX', max_length=20)),
                ('contact_address', models.TextField(default='Mumbai, India')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Content',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/testimonials/')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('testimonial', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='users.landingpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(default='Monthly', max_length=50)),
                ('features', models.TextField(help_text='One feature per line')),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='users.landingpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-star', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='users.landingpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
