# Generated by Django 4.2.16 on 2026-05-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('screenshot', models.ImageField(upload_to='deposits/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('wallet_type', models.CharField(choices=[('income', 'Income Wallet'), ('self_income', 'Self Income Wallet'), ('booster', 'Booster Income Wallet'), ('star', 'Star Income Wallet'), ('trading_level', 'Trading Level Income Wallet'), ('salary', 'Salary Wallet'), ('reward', 'Reward Income'), ('growth', 'Growth Income Wallet'), ('sponsor_growth', 'Sponsor Growth Income'), ('usdt', 'USDT Wallet'), ('topup', 'Topup Wallet')], max_length=30)),
                ('upi_or_address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
