# Generated by Django 4.2.16 on 2026-05-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=50)),
                ('achieved_at', models.DateField(auto_now_add=True)),
                ('reward_given', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
    ]
