# Generated by Django 4.2.16 on 2026-05-10 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_wallet', models.CharField(choices=[('income', 'Income Wallet'), ('self_income', 'Self Income Wallet'), ('booster', 'Booster Income Wallet'), ('star', 'Star Income Wallet'), ('trading_level', 'Trading Level Income Wallet'), ('salary', 'Salary Wallet'), ('reward', 'Reward Income'), ('growth', 'Growth Income Wallet'), ('sponsor_growth', 'Sponsor Growth Income'), ('usdt', 'USDT Wallet'), ('topup', 'Topup Wallet')], max_length=30)),
                ('to_wallet', models.CharField(choices=[('income', 'Income Wallet'), ('self_income', 'Self Income Wallet'), ('booster', 'Booster Income Wallet'), ('star', 'Star Income Wallet'), ('trading_level', 'Trading Level Income Wallet'), ('salary', 'Salary Wallet'), ('reward', 'Reward Income'), ('growth', 'Growth Income Wallet'), ('sponsor_growth', 'Sponsor Growth Income'), ('usdt', 'USDT Wallet'), ('topup', 'Topup Wallet')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('income', 'Income Wallet'), ('self_income', 'Self Income Wallet'), ('booster', 'Booster Income Wallet'), ('star', 'Star Income Wallet'), ('trading_level', 'Trading Level Income Wallet'), ('salary', 'Salary Wallet'), ('reward', 'Reward Income'), ('growth', 'Growth Income Wallet'), ('sponsor_growth', 'Sponsor Growth Income'), ('usdt', 'USDT Wallet'), ('topup', 'Topup Wallet')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('txn_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_txns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
